---
title: "Session_2"
author: "Gijs Custers"
date: "18 mei 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Exercise set 3, Task 6-11

``` {r}

library(tidyverse)
data(mpg, package = "ggplot2")
mpg %>% tbl_df

mpg %>% select(manufacturer, model, displ, year, cyl, trans, cty, hwy)
mpg2 <- mpg %>% select(manufacturer, model, displ, year, cyl, trans, cty, hwy)

mpg2 %>% mutate(displ2 = displ^2, vol_per_cyl = displ/cyl)

mpg3 <- mpg2 %>% mutate(displ2 = displ^2, vol_per_cyl = displ/cyl)
mpg3 %>% arrange(desc(vol_per_cyl))

mpg3 %>% filter(manufacturer == "chevrolet") %>% arrange(desc(vol_per_cyl))

mpg4 <- mpg3 %>% group_by(manufacturer, year) %>% summarise(max_vol_per_cyl = max(vol_per_cyl))

library(tidyr)

mpg5 <- mpg4 %>% spread(year,max_vol_per_cyl)

mpg6 <- mpg5 %>% mutate(change = `2008`-`1999`)

mpg6

mpg6 %>% rename(max_vpc_1999 = `1999`, max_vpc_2008 = `2008`) %>% gather(variable, value, max_vpc_1999, max_vpc_2008, change) %>% View


```


Exercise set 4 Task 12-14

``` {r}

install.packages("nycflights13")
library(tidyverse)
library(nycflights13)
flights %>% tbl_df

flights2 <- flights %>% select(origin, year, month, day, hour, 
    sched_dep_time, dep_delay, carrier)
weather2 <- weather %>% select(origin, year, month, day, hour, 
    precip, wind_speed, visib)

inner_join(flights2,weather2)
# Joining, by = c("origin", "year", "month", "day", "hour")

flights2 %>%  full_join(weather2)

weather2 %>% summarise(min_precip = min(precip, na.rm = TRUE), 
    min_wind = min(wind_speed, na.rm = TRUE), max_visib = max(visib, 
        na.rm = TRUE))

good_weather_delays <- inner_join(flights2,weather2) %>% filter(precip == min(precip,na.rm = TRUE) & wind_speed == min(wind_speed,na.rm = TRUE) & visib == max(visib,na.rm = TRUE))

good_weather_delays %>% View

good_weather_delays %>% group_by(carrier) %>% summarise(mean(dep_delay)) %>% arrange(mean(dep_delay)) %>% left_join(airlines)

good_weather_delays %>% group_by(carrier) %>% summarise(dep_delay = mean(dep_delay)) %>% arrange(dep_delay) %>% left_join(airlines)
## why some carriers get NA??

```
